name: Test(Go)

on:
  workflow_call:
    # For now, inputs supports only three types: 'boolean', 'number' or 'string'.
    # workaround: https://github.com/orgs/community/discussions/11692#discussioncomment-3541856
    inputs:
      os-versions:
        description: 'Stringfied JSON object listing GitHub-hosted runnners'
        default: '["ubuntu-24.04", "windows-2025", "macos-15"]'
        required: false
        type: string
      go-versions:
        description: 'Stringfied JSON object listing target Go versions'
        default: '["1.26.x", "1.25.x"]'
        required: false
        type: string

jobs:
  test:
    strategy:
      matrix:
        os: ${{ fromJson(inputs.os-versions) }}
        go: ${{ fromJson(inputs.go-versions) }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version: ${{ matrix.go }}
    - run: |
        go test -race -covermode=atomic -coverprofile=cover.out ./...
        if go tool -n gocover-cobertura &>/dev/null
        then
          go tool gocover-cobertura <cover.out >cover.xml
          echo 'cover=cover.xml' >>$GITHUB_OUTPUT
        fi
      shell: bash
      id: test
    - if: steps.test.outputs.cover != ''
      uses: actions/upload-code-coverage@abb5995db9e0199b0e2bb9dbd136fce4cb1ec4d3 # v1.3.0
      with:
        file: ${{ steps.test.outputs.cover }}
        language: Go
        label: code-coverage/${{ matrix.os }}_${{ matrix.go }}
